package String;
/*Problem Statement: 
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.*/

import java.util.*;
// this is one way i solved this problem : 3ms
class Solution 
{
    public char findTheDifference(String s, String t) 
    {
           int sum1=0,sum2=0,i=0,j=0;
           while(i<s.length())
           {
            int x=(int)s.charAt(i);
            sum1+=x;
            i++;
           }
           while(j<t.length())
           {
            int y=(int)t.charAt(j);
            sum2+=y;
            j++;
           }
           return (char)(sum2-sum1);
     }
}

//this is another way i solved the problem: 10ms
class Test
{
    public char findTheDifference(String x, String y)
    {
                Map<Character,Integer> a=new HashMap<>();
                Map<Character,Integer> b=new HashMap<>();
                for(char ch:x.toCharArray())
                {
                    a.put(ch,a.getOrDefault(ch,0)+1);
                }
                for(char ch1:y.toCharArray())
                {
                    b.put(ch1,b.getOrDefault(ch1,0)+1);
                }
                for(int i=0;i<y.length();i++)
                {
                    if(a.get(y.charAt(i)) == null)
                        return y.charAt(i);
                    else if(b.get(y.charAt(i))>a.get(y.charAt(i)))
                        return y.charAt(i);
                }
                return ' ';
    }
}
public class findDifference {
    public static void main(String args[]){
        Scanner sc=new Scanner(System.in);
        Solution n=new Solution();
        Test T=new Test();
        System.out.print("Enter the first string: ");
        String s=sc.nextLine();
        System.out.print("Enter the second string: ");
        String t=sc.nextLine();
        System.out.println("The difference between both the strings is: "+ n.findTheDifference(s,t));
        System.out.println("The difference between both the strings using HashMaps: "+ T.findTheDifference(s,t));
        sc.close();
    }
}
